nameOverride: "minio-storage"

rootUser: "madeirajunior"
rootPassword: "5241@Jrs"

replicas: 4

persistence:
  enabled: true
  storageClass: "local-path"
  size: 20Gi
  accessMode: ReadWriteOnce

service:
  type: ClusterIP
  clusterIP: ~
  port: "9000"

ingress:
  enabled: true
  labels: {}
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 10g
  path: /
  hosts:
    - minio.madeira.com
  tls: []

consoleService:
  type: ClusterIP
  clusterIP: ~
  ## Make sure to match it to minioConsolePort
  port: "9001"
  nodePort: 32001

consoleIngress:
  enabled: true
  labels: {}
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 10g
  path: /
  hosts:
    - console-minio.madeira.com
  tls: []

resources:
  requests:
    memory: 2Gi

tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
